package erpsolwcp.erpsolwcpmodel.erpsolwcpvo;

import erpsolwcp.erpsolwcpmodel.erpsolwcpeo.InSetPackingImpl;

import java.text.SimpleDateFormat;

import java.util.Calendar;

import oracle.jbo.Row;
import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.domain.Date;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Dec 16 18:50:14 PKT 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class InSetPackingViewRowImpl extends ViewRowImpl {

    public static final int ENTITY_INSETPACKING = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        Pckid,
        Locationid,
        Regionid,
        Itemid,
        Ptype,
        Pdate,
        Purchdate,
        Expdate,
        Posted,
        Postedby,
        Createdby,
        CreatedDate,
        Modifiedby,
        ModifiedDate,
        Remarks,
        Scpid,
        AllowedWpr,
        PrintInc,
        Packingseq,
        txtItemName,
        txtTotalTransactionIMEI,
        txtTotalBox,
        txtPerBoxImei,
        txtImeiSerial,
        InSpboxView,
        InItemsView,
        AccInItemsView,
        AccVWYesNoQVO;
        static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }

    public static final int PCKID = AttributesEnum.Pckid.index();
    public static final int LOCATIONID = AttributesEnum.Locationid.index();
    public static final int REGIONID = AttributesEnum.Regionid.index();
    public static final int ITEMID = AttributesEnum.Itemid.index();
    public static final int PTYPE = AttributesEnum.Ptype.index();
    public static final int PDATE = AttributesEnum.Pdate.index();
    public static final int PURCHDATE = AttributesEnum.Purchdate.index();
    public static final int EXPDATE = AttributesEnum.Expdate.index();
    public static final int POSTED = AttributesEnum.Posted.index();
    public static final int POSTEDBY = AttributesEnum.Postedby.index();
    public static final int CREATEDBY = AttributesEnum.Createdby.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int MODIFIEDBY = AttributesEnum.Modifiedby.index();
    public static final int MODIFIEDDATE = AttributesEnum.ModifiedDate.index();
    public static final int REMARKS = AttributesEnum.Remarks.index();
    public static final int SCPID = AttributesEnum.Scpid.index();
    public static final int ALLOWEDWPR = AttributesEnum.AllowedWpr.index();
    public static final int PRINTINC = AttributesEnum.PrintInc.index();
    public static final int PACKINGSEQ = AttributesEnum.Packingseq.index();
    public static final int TXTITEMNAME = AttributesEnum.txtItemName.index();
    public static final int TXTTOTALTRANSACTIONIMEI = AttributesEnum.txtTotalTransactionIMEI.index();
    public static final int TXTTOTALBOX = AttributesEnum.txtTotalBox.index();
    public static final int TXTPERBOXIMEI = AttributesEnum.txtPerBoxImei.index();
    public static final int TXTIMEISERIAL = AttributesEnum.txtImeiSerial.index();
    public static final int INSPBOXVIEW = AttributesEnum.InSpboxView.index();
    public static final int INITEMSVIEW = AttributesEnum.InItemsView.index();
    public static final int ACCINITEMSVIEW = AttributesEnum.AccInItemsView.index();
    public static final int ACCVWYESNOQVO = AttributesEnum.AccVWYesNoQVO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public InSetPackingViewRowImpl() {
    }

    /**
     * Gets InSetPacking entity object.
     * @return the InSetPacking
     */
    public InSetPackingImpl getInSetPacking() {
        return (InSetPackingImpl) getEntity(ENTITY_INSETPACKING);
    }

    /**
     * Gets the attribute value for PCKID using the alias name Pckid.
     * @return the PCKID
     */
    public String getPckid() {
        return (String) getAttributeInternal(PCKID);
    }

    /**
     * Sets <code>value</code> as attribute value for PCKID using the alias name Pckid.
     * @param value value to set the PCKID
     */
    public void setPckid(String value) {
        setAttributeInternal(PCKID, value);
    }

    /**
     * Gets the attribute value for LOCATIONID using the alias name Locationid.
     * @return the LOCATIONID
     */
    public String getLocationid() {
        return (String) getAttributeInternal(LOCATIONID);
    }

    /**
     * Sets <code>value</code> as attribute value for LOCATIONID using the alias name Locationid.
     * @param value value to set the LOCATIONID
     */
    public void setLocationid(String value) {
        setAttributeInternal(LOCATIONID, value);
    }

    /**
     * Gets the attribute value for REGIONID using the alias name Regionid.
     * @return the REGIONID
     */
    public String getRegionid() {
        return (String) getAttributeInternal(REGIONID);
    }

    /**
     * Sets <code>value</code> as attribute value for REGIONID using the alias name Regionid.
     * @param value value to set the REGIONID
     */
    public void setRegionid(String value) {
        setAttributeInternal(REGIONID, value);
    }

    /**
     * Gets the attribute value for ITEMID using the alias name Itemid.
     * @return the ITEMID
     */
    public String getItemid() {
        return (String) getAttributeInternal(ITEMID);
    }

    /**
     * Sets <code>value</code> as attribute value for ITEMID using the alias name Itemid.
     * @param value value to set the ITEMID
     */
    public void setItemid(String value) {
        setAttributeInternal(ITEMID, value);
    }

    /**
     * Gets the attribute value for PTYPE using the alias name Ptype.
     * @return the PTYPE
     */
    public String getPtype() {
        return (String) getAttributeInternal(PTYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for PTYPE using the alias name Ptype.
     * @param value value to set the PTYPE
     */
    public void setPtype(String value) {
        setAttributeInternal(PTYPE, value);
    }

    /**
     * Gets the attribute value for PDATE using the alias name Pdate.
     * @return the PDATE
     */
    public Date getPdate() {
        return (Date) getAttributeInternal(PDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for PDATE using the alias name Pdate.
     * @param value value to set the PDATE
     */
    public void setPdate(Date value) {
        setAttributeInternal(PDATE, value);
    }

    /**
     * Gets the attribute value for PURCHDATE using the alias name Purchdate.
     * @return the PURCHDATE
     */
    public Date getPurchdate() {
        return (Date) getAttributeInternal(PURCHDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for PURCHDATE using the alias name Purchdate.
     * @param value value to set the PURCHDATE
     */
    public void setPurchdate(Date value) {
        setAttributeInternal(PURCHDATE, value);
    }

    /**
     * Gets the attribute value for EXPDATE using the alias name Expdate.
     * @return the EXPDATE
     */
    public Date getExpdate() {
        return (Date) getAttributeInternal(EXPDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for EXPDATE using the alias name Expdate.
     * @param value value to set the EXPDATE
     */
    public void setExpdate(Date value) {
        setAttributeInternal(EXPDATE, value);
    }

    /**
     * Gets the attribute value for POSTED using the alias name Posted.
     * @return the POSTED
     */
    public String getPosted() {
        return (String) getAttributeInternal(POSTED);
    }

    /**
     * Sets <code>value</code> as attribute value for POSTED using the alias name Posted.
     * @param value value to set the POSTED
     */
    public void setPosted(String value) {
        setAttributeInternal(POSTED, value);
    }

    /**
     * Gets the attribute value for POSTEDBY using the alias name Postedby.
     * @return the POSTEDBY
     */
    public String getPostedby() {
        return (String) getAttributeInternal(POSTEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for POSTEDBY using the alias name Postedby.
     * @param value value to set the POSTEDBY
     */
    public void setPostedby(String value) {
        setAttributeInternal(POSTEDBY, value);
    }

    /**
     * Gets the attribute value for CREATEDBY using the alias name Createdby.
     * @return the CREATEDBY
     */
    public String getCreatedby() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATEDBY using the alias name Createdby.
     * @param value value to set the CREATEDBY
     */
    public void setCreatedby(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CREATED_DATE using the alias name CreatedDate.
     * @return the CREATED_DATE
     */
    public Date getCreatedDate() {
        return (Date) getAttributeInternal(CREATEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_DATE using the alias name CreatedDate.
     * @param value value to set the CREATED_DATE
     */
    public void setCreatedDate(Date value) {
        setAttributeInternal(CREATEDDATE, value);
    }

    /**
     * Gets the attribute value for MODIFIEDBY using the alias name Modifiedby.
     * @return the MODIFIEDBY
     */
    public String getModifiedby() {
        return (String) getAttributeInternal(MODIFIEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for MODIFIEDBY using the alias name Modifiedby.
     * @param value value to set the MODIFIEDBY
     */
    public void setModifiedby(String value) {
        setAttributeInternal(MODIFIEDBY, value);
    }

    /**
     * Gets the attribute value for MODIFIED_DATE using the alias name ModifiedDate.
     * @return the MODIFIED_DATE
     */
    public Date getModifiedDate() {
        return (Date) getAttributeInternal(MODIFIEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for MODIFIED_DATE using the alias name ModifiedDate.
     * @param value value to set the MODIFIED_DATE
     */
    public void setModifiedDate(Date value) {
        setAttributeInternal(MODIFIEDDATE, value);
    }

    /**
     * Gets the attribute value for REMARKS using the alias name Remarks.
     * @return the REMARKS
     */
    public String getRemarks() {
        return (String) getAttributeInternal(REMARKS);
    }

    /**
     * Sets <code>value</code> as attribute value for REMARKS using the alias name Remarks.
     * @param value value to set the REMARKS
     */
    public void setRemarks(String value) {
        setAttributeInternal(REMARKS, value);
    }

    /**
     * Gets the attribute value for SCPID using the alias name Scpid.
     * @return the SCPID
     */
    public String getScpid() {
        return (String) getAttributeInternal(SCPID);
    }

    /**
     * Sets <code>value</code> as attribute value for SCPID using the alias name Scpid.
     * @param value value to set the SCPID
     */
    public void setScpid(String value) {
        setAttributeInternal(SCPID, value);
    }

    /**
     * Gets the attribute value for ALLOWED_WPR using the alias name AllowedWpr.
     * @return the ALLOWED_WPR
     */
    public String getAllowedWpr() {
        return (String) getAttributeInternal(ALLOWEDWPR);
    }

    /**
     * Sets <code>value</code> as attribute value for ALLOWED_WPR using the alias name AllowedWpr.
     * @param value value to set the ALLOWED_WPR
     */
    public void setAllowedWpr(String value) {
        setAttributeInternal(ALLOWEDWPR, value);
    }

    /**
     * Gets the attribute value for PRINT_INC using the alias name PrintInc.
     * @return the PRINT_INC
     */
    public String getPrintInc() {
        return (String) getAttributeInternal(PRINTINC);
    }

    /**
     * Sets <code>value</code> as attribute value for PRINT_INC using the alias name PrintInc.
     * @param value value to set the PRINT_INC
     */
    public void setPrintInc(String value) {
        setAttributeInternal(PRINTINC, value);
    }

    /**
     * Gets the attribute value for PACKINGSEQ using the alias name Packingseq.
     * @return the PACKINGSEQ
     */
    public Integer getPackingseq() {
        return (Integer) getAttributeInternal(PACKINGSEQ);
    }

    /**
     * Sets <code>value</code> as attribute value for PACKINGSEQ using the alias name Packingseq.
     * @param value value to set the PACKINGSEQ
     */
    public void setPackingseq(Integer value) {
        setAttributeInternal(PACKINGSEQ, value);
    }

    /**
     * Gets the attribute value for TXT_ITEM_NAME using the alias name txtItemName.
     * @return the TXT_ITEM_NAME
     */
    public String gettxtItemName() {
        return (String) getAttributeInternal(TXTITEMNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for TXT_ITEM_NAME using the alias name txtItemName.
     * @param value value to set the TXT_ITEM_NAME
     */
    public void settxtItemName(String value) {
        setAttributeInternal(TXTITEMNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute txtTotalTransactionIMEI.
     * @return the txtTotalTransactionIMEI
     */
    public Integer gettxtTotalTransactionIMEI() {
        return (Integer) getAttributeInternal(TXTTOTALTRANSACTIONIMEI);
    }

    /**
     * Gets the attribute value for the calculated attribute txtTotalBox.
     * @return the txtTotalBox
     */
    public Integer gettxtTotalBox() {
        return (Integer) getAttributeInternal(TXTTOTALBOX);
    }

    /**
     * Gets the attribute value for TXT_PER_BOX_IMEI using the alias name txtPerBoxImei.
     * @return the TXT_PER_BOX_IMEI
     */
    public Integer gettxtPerBoxImei() {
        return (Integer) getAttributeInternal(TXTPERBOXIMEI);
    }

    /**
     * Sets <code>value</code> as attribute value for TXT_PER_BOX_IMEI using the alias name txtPerBoxImei.
     * @param value value to set the TXT_PER_BOX_IMEI
     */
    public void settxtPerBoxImei(Integer value) {
        setAttributeInternal(TXTPERBOXIMEI, value);
    }

    /**
     * Gets the attribute value for TXT_IMEI_SERIAL using the alias name txtImeiSerial.
     * @return the TXT_IMEI_SERIAL
     */
    public String gettxtImeiSerial() {
        return (String) getAttributeInternal(TXTIMEISERIAL);
    }

    /**
     * Sets <code>value</code> as attribute value for TXT_IMEI_SERIAL using the alias name txtImeiSerial.
     * @param value value to set the TXT_IMEI_SERIAL
     */
    public void settxtImeiSerial(String value) {
        setAttributeInternal(TXTIMEISERIAL, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link InSpboxView.
     */
    public RowIterator getInSpboxView() {
        return (RowIterator) getAttributeInternal(INSPBOXVIEW);
    }

    /**
     * Gets the associated <code>Row</code> using master-detail link InItemsView.
     */
    public Row getInItemsView() {
        return (Row) getAttributeInternal(INITEMSVIEW);
    }

    /**
     * Sets the master-detail link InItemsView between this object and <code>value</code>.
     */
    public void setInItemsView(Row value) {
        setAttributeInternal(INITEMSVIEW, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccInItemsView.
     */
    public RowSet getAccInItemsView() {
        return (RowSet) getAttributeInternal(ACCINITEMSVIEW);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccVWYesNoQVO.
     */
    public RowSet getAccVWYesNoQVO() {
        return (RowSet) getAttributeInternal(ACCVWYESNOQVO);
    }
    @Override
    public boolean isAttributeUpdateable(int i) {
        // TODO Implement this method
        if (getPosted().equals("Y")) {
            return false;
       }
        return super.isAttributeUpdateable(i);
    }
    
    public void ErpSolDoSetStartEndDate(Date pDate) throws Exception {
        Calendar calendar = Calendar.getInstance();
        java.util.Date UtilDate=new SimpleDateFormat("yyyy-mm-dddd").parse(pDate.toString());  
        calendar.setTime(UtilDate);
    }
    
}

