package erpsolwcp.erpsolwcpmodel.erpsolwcpvo;

import erpsolwcp.erpsolwcpmodel.erpsolwcpeo.InSetPackingScanImpl;

import oracle.jbo.Row;
import oracle.jbo.domain.Date;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Dec 24 13:58:28 PKT 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class InSetPackingScanViewRowImpl extends ViewRowImpl {
    public static final int ENTITY_INSETPACKINGSCAN = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        InSetPackingScanSeq,
        BoxNo,
        ImeiNo,
        Lineno,
        CreatedBy,
        CreatedDate,
        ModifiedBy,
        ModifiedDate,
        Packingseq,
        InSetPackingView;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int INSETPACKINGSCANSEQ = AttributesEnum.InSetPackingScanSeq.index();
    public static final int BOXNO = AttributesEnum.BoxNo.index();
    public static final int IMEINO = AttributesEnum.ImeiNo.index();
    public static final int LINENO = AttributesEnum.Lineno.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int MODIFIEDBY = AttributesEnum.ModifiedBy.index();
    public static final int MODIFIEDDATE = AttributesEnum.ModifiedDate.index();
    public static final int PACKINGSEQ = AttributesEnum.Packingseq.index();
    public static final int INSETPACKINGVIEW = AttributesEnum.InSetPackingView.index();

    /**
     * This is the default constructor (do not remove).
     */
    public InSetPackingScanViewRowImpl() {
    }

    /**
     * Gets InSetPackingScan entity object.
     * @return the InSetPackingScan
     */
    public InSetPackingScanImpl getInSetPackingScan() {
        return (InSetPackingScanImpl) getEntity(ENTITY_INSETPACKINGSCAN);
    }

    /**
     * Gets the attribute value for IN_SET_PACKING_SCAN_SEQ using the alias name InSetPackingScanSeq.
     * @return the IN_SET_PACKING_SCAN_SEQ
     */
    public Integer getInSetPackingScanSeq() {
        return (Integer) getAttributeInternal(INSETPACKINGSCANSEQ);
    }

    /**
     * Sets <code>value</code> as attribute value for IN_SET_PACKING_SCAN_SEQ using the alias name InSetPackingScanSeq.
     * @param value value to set the IN_SET_PACKING_SCAN_SEQ
     */
    public void setInSetPackingScanSeq(Integer value) {
        setAttributeInternal(INSETPACKINGSCANSEQ, value);
    }

    /**
     * Gets the attribute value for BOX_NO using the alias name BoxNo.
     * @return the BOX_NO
     */
    public String getBoxNo() {
        return (String) getAttributeInternal(BOXNO);
    }

    /**
     * Sets <code>value</code> as attribute value for BOX_NO using the alias name BoxNo.
     * @param value value to set the BOX_NO
     */
    public void setBoxNo(String value) {
        setAttributeInternal(BOXNO, value);
    }

    /**
     * Gets the attribute value for IMEI_NO using the alias name ImeiNo.
     * @return the IMEI_NO
     */
    public String getImeiNo() {
        return (String) getAttributeInternal(IMEINO);
    }

    /**
     * Sets <code>value</code> as attribute value for IMEI_NO using the alias name ImeiNo.
     * @param value value to set the IMEI_NO
     */
    public void setImeiNo(String value) {
        setAttributeInternal(IMEINO, value);
        getDBTransaction().commit();
    }

    /**
     * Gets the attribute value for LINENO using the alias name Lineno.
     * @return the LINENO
     */
    public Integer getLineno() {
        return (Integer) getAttributeInternal(LINENO);
    }

    /**
     * Sets <code>value</code> as attribute value for LINENO using the alias name Lineno.
     * @param value value to set the LINENO
     */
    public void setLineno(Integer value) {
        setAttributeInternal(LINENO, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CREATED_DATE using the alias name CreatedDate.
     * @return the CREATED_DATE
     */
    public Date getCreatedDate() {
        return (Date) getAttributeInternal(CREATEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_DATE using the alias name CreatedDate.
     * @param value value to set the CREATED_DATE
     */
    public void setCreatedDate(Date value) {
        setAttributeInternal(CREATEDDATE, value);
    }

    /**
     * Gets the attribute value for MODIFIED_BY using the alias name ModifiedBy.
     * @return the MODIFIED_BY
     */
    public String getModifiedBy() {
        return (String) getAttributeInternal(MODIFIEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for MODIFIED_BY using the alias name ModifiedBy.
     * @param value value to set the MODIFIED_BY
     */
    public void setModifiedBy(String value) {
        setAttributeInternal(MODIFIEDBY, value);
    }

    /**
     * Gets the attribute value for MODIFIED_DATE using the alias name ModifiedDate.
     * @return the MODIFIED_DATE
     */
    public Date getModifiedDate() {
        return (Date) getAttributeInternal(MODIFIEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for MODIFIED_DATE using the alias name ModifiedDate.
     * @param value value to set the MODIFIED_DATE
     */
    public void setModifiedDate(Date value) {
        setAttributeInternal(MODIFIEDDATE, value);
    }

    /**
     * Gets the attribute value for PACKINGSEQ using the alias name Packingseq.
     * @return the PACKINGSEQ
     */
    public Integer getPackingseq() {
        return (Integer) getAttributeInternal(PACKINGSEQ);
    }

    /**
     * Sets <code>value</code> as attribute value for PACKINGSEQ using the alias name Packingseq.
     * @param value value to set the PACKINGSEQ
     */
    public void setPackingseq(Integer value) {
        setAttributeInternal(PACKINGSEQ, value);
    }

    /**
     * Gets the associated <code>Row</code> using master-detail link InSetPackingView.
     */
    public Row getInSetPackingView() {
        return (Row) getAttributeInternal(INSETPACKINGVIEW);
    }

    /**
     * Sets the master-detail link InSetPackingView between this object and <code>value</code>.
     */
    public void setInSetPackingView(Row value) {
        setAttributeInternal(INSETPACKINGVIEW, value);
    }
}

