package erpsolwcp.erpsolwcpmodel.erpsolwcpvo;

import erpsolwcp.erpsolwcpmodel.erpsolwcpeo.InSpdetlImpl;

import java.math.BigDecimal;

import oracle.jbo.Row;
import oracle.jbo.domain.Date;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Dec 16 18:51:23 PKT 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class InSpdetlViewRowImpl extends ViewRowImpl {
    public static final int ENTITY_INSPDETL = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        Pckdetlid,
        ImeiNo,
        Code,
        Phoneno,
        Msg,
        Createdby,
        CreatedDate,
        Modifiedby,
        ModifiedDate,
        Storeid,
        Status,
        Incentive,
        IncentiveMsg,
        Chk,
        SerialNo,
        IncPst,
        Spboxseq,
        Spdetlseq,
        InSpboxView;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int PCKDETLID = AttributesEnum.Pckdetlid.index();
    public static final int IMEINO = AttributesEnum.ImeiNo.index();
    public static final int CODE = AttributesEnum.Code.index();
    public static final int PHONENO = AttributesEnum.Phoneno.index();
    public static final int MSG = AttributesEnum.Msg.index();
    public static final int CREATEDBY = AttributesEnum.Createdby.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int MODIFIEDBY = AttributesEnum.Modifiedby.index();
    public static final int MODIFIEDDATE = AttributesEnum.ModifiedDate.index();
    public static final int STOREID = AttributesEnum.Storeid.index();
    public static final int STATUS = AttributesEnum.Status.index();
    public static final int INCENTIVE = AttributesEnum.Incentive.index();
    public static final int INCENTIVEMSG = AttributesEnum.IncentiveMsg.index();
    public static final int CHK = AttributesEnum.Chk.index();
    public static final int SERIALNO = AttributesEnum.SerialNo.index();
    public static final int INCPST = AttributesEnum.IncPst.index();
    public static final int SPBOXSEQ = AttributesEnum.Spboxseq.index();
    public static final int SPDETLSEQ = AttributesEnum.Spdetlseq.index();
    public static final int INSPBOXVIEW = AttributesEnum.InSpboxView.index();

    /**
     * This is the default constructor (do not remove).
     */
    public InSpdetlViewRowImpl() {
    }

    /**
     * Gets InSpdetl entity object.
     * @return the InSpdetl
     */
    public InSpdetlImpl getInSpdetl() {
        return (InSpdetlImpl) getEntity(ENTITY_INSPDETL);
    }

    /**
     * Gets the attribute value for PCKDETLID using the alias name Pckdetlid.
     * @return the PCKDETLID
     */
    public String getPckdetlid() {
        return (String) getAttributeInternal(PCKDETLID);
    }

    /**
     * Sets <code>value</code> as attribute value for PCKDETLID using the alias name Pckdetlid.
     * @param value value to set the PCKDETLID
     */
    public void setPckdetlid(String value) {
        setAttributeInternal(PCKDETLID, value);
    }

    /**
     * Gets the attribute value for IMEI_NO using the alias name ImeiNo.
     * @return the IMEI_NO
     */
    public String getImeiNo() {
        return (String) getAttributeInternal(IMEINO);
    }

    /**
     * Sets <code>value</code> as attribute value for IMEI_NO using the alias name ImeiNo.
     * @param value value to set the IMEI_NO
     */
    public void setImeiNo(String value) {
        setAttributeInternal(IMEINO, value);
    }

    /**
     * Gets the attribute value for CODE using the alias name Code.
     * @return the CODE
     */
    public String getCode() {
        return (String) getAttributeInternal(CODE);
    }

    /**
     * Sets <code>value</code> as attribute value for CODE using the alias name Code.
     * @param value value to set the CODE
     */
    public void setCode(String value) {
        setAttributeInternal(CODE, value);
    }

    /**
     * Gets the attribute value for PHONENO using the alias name Phoneno.
     * @return the PHONENO
     */
    public String getPhoneno() {
        return (String) getAttributeInternal(PHONENO);
    }

    /**
     * Sets <code>value</code> as attribute value for PHONENO using the alias name Phoneno.
     * @param value value to set the PHONENO
     */
    public void setPhoneno(String value) {
        setAttributeInternal(PHONENO, value);
    }

    /**
     * Gets the attribute value for MSG using the alias name Msg.
     * @return the MSG
     */
    public String getMsg() {
        return (String) getAttributeInternal(MSG);
    }

    /**
     * Sets <code>value</code> as attribute value for MSG using the alias name Msg.
     * @param value value to set the MSG
     */
    public void setMsg(String value) {
        setAttributeInternal(MSG, value);
    }

    /**
     * Gets the attribute value for CREATEDBY using the alias name Createdby.
     * @return the CREATEDBY
     */
    public String getCreatedby() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATEDBY using the alias name Createdby.
     * @param value value to set the CREATEDBY
     */
    public void setCreatedby(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CREATED_DATE using the alias name CreatedDate.
     * @return the CREATED_DATE
     */
    public Date getCreatedDate() {
        return (Date) getAttributeInternal(CREATEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_DATE using the alias name CreatedDate.
     * @param value value to set the CREATED_DATE
     */
    public void setCreatedDate(Date value) {
        setAttributeInternal(CREATEDDATE, value);
    }

    /**
     * Gets the attribute value for MODIFIEDBY using the alias name Modifiedby.
     * @return the MODIFIEDBY
     */
    public String getModifiedby() {
        return (String) getAttributeInternal(MODIFIEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for MODIFIEDBY using the alias name Modifiedby.
     * @param value value to set the MODIFIEDBY
     */
    public void setModifiedby(String value) {
        setAttributeInternal(MODIFIEDBY, value);
    }

    /**
     * Gets the attribute value for MODIFIED_DATE using the alias name ModifiedDate.
     * @return the MODIFIED_DATE
     */
    public Date getModifiedDate() {
        return (Date) getAttributeInternal(MODIFIEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for MODIFIED_DATE using the alias name ModifiedDate.
     * @param value value to set the MODIFIED_DATE
     */
    public void setModifiedDate(Date value) {
        setAttributeInternal(MODIFIEDDATE, value);
    }

    /**
     * Gets the attribute value for STOREID using the alias name Storeid.
     * @return the STOREID
     */
    public String getStoreid() {
        return (String) getAttributeInternal(STOREID);
    }

    /**
     * Sets <code>value</code> as attribute value for STOREID using the alias name Storeid.
     * @param value value to set the STOREID
     */
    public void setStoreid(String value) {
        setAttributeInternal(STOREID, value);
    }

    /**
     * Gets the attribute value for STATUS using the alias name Status.
     * @return the STATUS
     */
    public String getStatus() {
        return (String) getAttributeInternal(STATUS);
    }

    /**
     * Sets <code>value</code> as attribute value for STATUS using the alias name Status.
     * @param value value to set the STATUS
     */
    public void setStatus(String value) {
        setAttributeInternal(STATUS, value);
    }

    /**
     * Gets the attribute value for INCENTIVE using the alias name Incentive.
     * @return the INCENTIVE
     */
    public BigDecimal getIncentive() {
        return (BigDecimal) getAttributeInternal(INCENTIVE);
    }

    /**
     * Sets <code>value</code> as attribute value for INCENTIVE using the alias name Incentive.
     * @param value value to set the INCENTIVE
     */
    public void setIncentive(BigDecimal value) {
        setAttributeInternal(INCENTIVE, value);
    }

    /**
     * Gets the attribute value for INCENTIVE_MSG using the alias name IncentiveMsg.
     * @return the INCENTIVE_MSG
     */
    public String getIncentiveMsg() {
        return (String) getAttributeInternal(INCENTIVEMSG);
    }

    /**
     * Sets <code>value</code> as attribute value for INCENTIVE_MSG using the alias name IncentiveMsg.
     * @param value value to set the INCENTIVE_MSG
     */
    public void setIncentiveMsg(String value) {
        setAttributeInternal(INCENTIVEMSG, value);
    }

    /**
     * Gets the attribute value for CHK using the alias name Chk.
     * @return the CHK
     */
    public String getChk() {
        return (String) getAttributeInternal(CHK);
    }

    /**
     * Sets <code>value</code> as attribute value for CHK using the alias name Chk.
     * @param value value to set the CHK
     */
    public void setChk(String value) {
        setAttributeInternal(CHK, value);
    }

    /**
     * Gets the attribute value for SERIAL_NO using the alias name SerialNo.
     * @return the SERIAL_NO
     */
    public String getSerialNo() {
        return (String) getAttributeInternal(SERIALNO);
    }

    /**
     * Sets <code>value</code> as attribute value for SERIAL_NO using the alias name SerialNo.
     * @param value value to set the SERIAL_NO
     */
    public void setSerialNo(String value) {
        setAttributeInternal(SERIALNO, value);
    }

    /**
     * Gets the attribute value for INC_PST using the alias name IncPst.
     * @return the INC_PST
     */
    public BigDecimal getIncPst() {
        return (BigDecimal) getAttributeInternal(INCPST);
    }

    /**
     * Sets <code>value</code> as attribute value for INC_PST using the alias name IncPst.
     * @param value value to set the INC_PST
     */
    public void setIncPst(BigDecimal value) {
        setAttributeInternal(INCPST, value);
    }

    /**
     * Gets the attribute value for SPBOXSEQ using the alias name Spboxseq.
     * @return the SPBOXSEQ
     */
    public Integer getSpboxseq() {
        return (Integer) getAttributeInternal(SPBOXSEQ);
    }

    /**
     * Sets <code>value</code> as attribute value for SPBOXSEQ using the alias name Spboxseq.
     * @param value value to set the SPBOXSEQ
     */
    public void setSpboxseq(Integer value) {
        setAttributeInternal(SPBOXSEQ, value);
    }

    /**
     * Gets the attribute value for SPDETLSEQ using the alias name Spdetlseq.
     * @return the SPDETLSEQ
     */
    public Integer getSpdetlseq() {
        return (Integer) getAttributeInternal(SPDETLSEQ);
    }

    /**
     * Sets <code>value</code> as attribute value for SPDETLSEQ using the alias name Spdetlseq.
     * @param value value to set the SPDETLSEQ
     */
    public void setSpdetlseq(Integer value) {
        setAttributeInternal(SPDETLSEQ, value);
    }

    /**
     * Gets the associated <code>Row</code> using master-detail link InSpboxView.
     */
    public Row getInSpboxView() {
        return (Row) getAttributeInternal(INSPBOXVIEW);
    }

    /**
     * Sets the master-detail link InSpboxView between this object and <code>value</code>.
     */
    public void setInSpboxView(Row value) {
        setAttributeInternal(INSPBOXVIEW, value);
    }
    
}

