package erpsolwcp.erpsolwcpmodel.erpsolwcpvo;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Dec 16 18:51:23 PKT 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class InSpdetlViewImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public InSpdetlViewImpl() {
    }
}

