package erpsolwcp.erpsolwcpmodel.erpsolwcpqvo.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jan 03 10:10:00 PKT 2022
// ---------------------------------------------------------------------
public interface VWWarrantyCardReportQVO extends ViewObject {
    void doERPSolUnsubmitWCP();
}

