package erpsolwcp.erpsolwcpmodel.erpsolwcpeo;

import erpsolglob.erpsolglobmodel.erpsolglobclasses.ERPSolGlobClassModel;
import erpsolglob.erpsolglobmodel.erpsolglobclasses.ERPSolGlobalsEntityImpl;

import java.text.SimpleDateFormat;

import java.util.Calendar;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.domain.Date;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Nov 29 16:01:05 PKT 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class InSetPackingImpl extends ERPSolGlobalsEntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        Pckid,
        Locationid,
        Regionid,
        Itemid,
        Ptype,
        Pdate,
        Purchdate,
        Expdate,
        Posted,
        Postedby,
        Createdby,
        CreatedDate,
        Modifiedby,
        ModifiedDate,
        Remarks,
        Scpid,
        AllowedWpr,
        PrintInc,
        Packingseq,
        txtItemName,
        txtPerBoxImei,
        txtImeiSerial,
        InSpbox,
        InItems;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int PCKID = AttributesEnum.Pckid.index();
    public static final int LOCATIONID = AttributesEnum.Locationid.index();
    public static final int REGIONID = AttributesEnum.Regionid.index();
    public static final int ITEMID = AttributesEnum.Itemid.index();
    public static final int PTYPE = AttributesEnum.Ptype.index();
    public static final int PDATE = AttributesEnum.Pdate.index();
    public static final int PURCHDATE = AttributesEnum.Purchdate.index();
    public static final int EXPDATE = AttributesEnum.Expdate.index();
    public static final int POSTED = AttributesEnum.Posted.index();
    public static final int POSTEDBY = AttributesEnum.Postedby.index();
    public static final int CREATEDBY = AttributesEnum.Createdby.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int MODIFIEDBY = AttributesEnum.Modifiedby.index();
    public static final int MODIFIEDDATE = AttributesEnum.ModifiedDate.index();
    public static final int REMARKS = AttributesEnum.Remarks.index();
    public static final int SCPID = AttributesEnum.Scpid.index();
    public static final int ALLOWEDWPR = AttributesEnum.AllowedWpr.index();
    public static final int PRINTINC = AttributesEnum.PrintInc.index();
    public static final int PACKINGSEQ = AttributesEnum.Packingseq.index();
    public static final int TXTITEMNAME = AttributesEnum.txtItemName.index();
    public static final int TXTPERBOXIMEI = AttributesEnum.txtPerBoxImei.index();
    public static final int TXTIMEISERIAL = AttributesEnum.txtImeiSerial.index();
    public static final int INSPBOX = AttributesEnum.InSpbox.index();
    public static final int INITEMS = AttributesEnum.InItems.index();

    /**
     * This is the default constructor (do not remove).
     */
    public InSetPackingImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("erpsolwcp.erpsolwcpmodel.erpsolwcpeo.InSetPacking");
    }


    /**
     * Gets the attribute value for Pckid, using the alias name Pckid.
     * @return the value of Pckid
     */
    public String getPckid() {
        return (String) getAttributeInternal(PCKID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Pckid.
     * @param value value to set the Pckid
     */
    public void setPckid(String value) {
        setAttributeInternal(PCKID, value);
    }

    /**
     * Gets the attribute value for Locationid, using the alias name Locationid.
     * @return the value of Locationid
     */
    public String getLocationid() {
        return (String) getAttributeInternal(LOCATIONID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Locationid.
     * @param value value to set the Locationid
     */
    public void setLocationid(String value) {
        setAttributeInternal(LOCATIONID, value);
    }

    /**
     * Gets the attribute value for Regionid, using the alias name Regionid.
     * @return the value of Regionid
     */
    public String getRegionid() {
        return (String) getAttributeInternal(REGIONID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Regionid.
     * @param value value to set the Regionid
     */
    public void setRegionid(String value) {
        setAttributeInternal(REGIONID, value);
    }

    /**
     * Gets the attribute value for Itemid, using the alias name Itemid.
     * @return the value of Itemid
     */
    public String getItemid() {
        return (String) getAttributeInternal(ITEMID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Itemid.
     * @param value value to set the Itemid
     */
    public void setItemid(String value) {
        setAttributeInternal(ITEMID, value);
        doSetErpSolStartEndDate(getPdate().toString());
    }

    /**
     * Gets the attribute value for Ptype, using the alias name Ptype.
     * @return the value of Ptype
     */
    public String getPtype() {
        return (String) getAttributeInternal(PTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Ptype.
     * @param value value to set the Ptype
     */
    public void setPtype(String value) {
        setAttributeInternal(PTYPE, value);
    }

    /**
     * Gets the attribute value for Pdate, using the alias name Pdate.
     * @return the value of Pdate
     */
    public Date getPdate() {
        return (Date) getAttributeInternal(PDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Pdate.
     * @param value value to set the Pdate
     */
    public void setPdate(Date value) {
        setAttributeInternal(PDATE, value);
    }

    /**
     * Gets the attribute value for Purchdate, using the alias name Purchdate.
     * @return the value of Purchdate
     */
    public Date getPurchdate() {
        return (Date) getAttributeInternal(PURCHDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Purchdate.
     * @param value value to set the Purchdate
     */
    public void setPurchdate(Date value) {
        setAttributeInternal(PURCHDATE, value);
    }

    /**
     * Gets the attribute value for Expdate, using the alias name Expdate.
     * @return the value of Expdate
     */
    public Date getExpdate() {
        return (Date) getAttributeInternal(EXPDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Expdate.
     * @param value value to set the Expdate
     */
    public void setExpdate(Date value) {
        setAttributeInternal(EXPDATE, value);
    }

    /**
     * Gets the attribute value for Posted, using the alias name Posted.
     * @return the value of Posted
     */
    public String getPosted() {
        return (String) getAttributeInternal(POSTED);
    }

    /**
     * Sets <code>value</code> as the attribute value for Posted.
     * @param value value to set the Posted
     */
    public void setPosted(String value) {
        setAttributeInternal(POSTED, value);
    }

    /**
     * Gets the attribute value for Postedby, using the alias name Postedby.
     * @return the value of Postedby
     */
    public String getPostedby() {
        return (String) getAttributeInternal(POSTEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for Postedby.
     * @param value value to set the Postedby
     */
    public void setPostedby(String value) {
        setAttributeInternal(POSTEDBY, value);
    }

    /**
     * Gets the attribute value for Createdby, using the alias name Createdby.
     * @return the value of Createdby
     */
    public String getCreatedby() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for Createdby.
     * @param value value to set the Createdby
     */
    public void setCreatedby(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CreatedDate, using the alias name CreatedDate.
     * @return the value of CreatedDate
     */
    public Date getCreatedDate() {
        return (Date) getAttributeInternal(CREATEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedDate.
     * @param value value to set the CreatedDate
     */
    public void setCreatedDate(Date value) {
        setAttributeInternal(CREATEDDATE, value);
    }

    /**
     * Gets the attribute value for Modifiedby, using the alias name Modifiedby.
     * @return the value of Modifiedby
     */
    public String getModifiedby() {
        return (String) getAttributeInternal(MODIFIEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for Modifiedby.
     * @param value value to set the Modifiedby
     */
    public void setModifiedby(String value) {
        setAttributeInternal(MODIFIEDBY, value);
    }

    /**
     * Gets the attribute value for ModifiedDate, using the alias name ModifiedDate.
     * @return the value of ModifiedDate
     */
    public Date getModifiedDate() {
        return (Date) getAttributeInternal(MODIFIEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ModifiedDate.
     * @param value value to set the ModifiedDate
     */
    public void setModifiedDate(Date value) {
        setAttributeInternal(MODIFIEDDATE, value);
    }

    /**
     * Gets the attribute value for Remarks, using the alias name Remarks.
     * @return the value of Remarks
     */
    public String getRemarks() {
        return (String) getAttributeInternal(REMARKS);
    }

    /**
     * Sets <code>value</code> as the attribute value for Remarks.
     * @param value value to set the Remarks
     */
    public void setRemarks(String value) {
        setAttributeInternal(REMARKS, value);
    }

    /**
     * Gets the attribute value for Scpid, using the alias name Scpid.
     * @return the value of Scpid
     */
    public String getScpid() {
        return (String) getAttributeInternal(SCPID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Scpid.
     * @param value value to set the Scpid
     */
    public void setScpid(String value) {
        setAttributeInternal(SCPID, value);
    }

    /**
     * Gets the attribute value for AllowedWpr, using the alias name AllowedWpr.
     * @return the value of AllowedWpr
     */
    public String getAllowedWpr() {
        return (String) getAttributeInternal(ALLOWEDWPR);
    }

    /**
     * Sets <code>value</code> as the attribute value for AllowedWpr.
     * @param value value to set the AllowedWpr
     */
    public void setAllowedWpr(String value) {
        setAttributeInternal(ALLOWEDWPR, value);
    }

    /**
     * Gets the attribute value for PrintInc, using the alias name PrintInc.
     * @return the value of PrintInc
     */
    public String getPrintInc() {
        return (String) getAttributeInternal(PRINTINC);
    }

    /**
     * Sets <code>value</code> as the attribute value for PrintInc.
     * @param value value to set the PrintInc
     */
    public void setPrintInc(String value) {
        setAttributeInternal(PRINTINC, value);
    }

    /**
     * Gets the attribute value for Packingseq, using the alias name Packingseq.
     * @return the value of Packingseq
     */
    public Integer getPackingseq() {
        return (Integer) getAttributeInternal(PACKINGSEQ);
    }

    /**
     * Sets <code>value</code> as the attribute value for Packingseq.
     * @param value value to set the Packingseq
     */
    public void setPackingseq(Integer value) {
        setAttributeInternal(PACKINGSEQ, value);
    }

    /**
     * Gets the attribute value for txtItemName, using the alias name txtItemName.
     * @return the value of txtItemName
     */
    public String gettxtItemName() {
        return (String) getAttributeInternal(TXTITEMNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for txtItemName.
     * @param value value to set the txtItemName
     */
    public void settxtItemName(String value) {
        setAttributeInternal(TXTITEMNAME, value);
    }

    /**
     * Gets the attribute value for txtPerBoxImei, using the alias name txtPerBoxImei.
     * @return the value of txtPerBoxImei
     */
    public Integer gettxtPerBoxImei() {
        return (Integer) getAttributeInternal(TXTPERBOXIMEI);
    }

    /**
     * Sets <code>value</code> as the attribute value for txtPerBoxImei.
     * @param value value to set the txtPerBoxImei
     */
    public void settxtPerBoxImei(Integer value) {
        setAttributeInternal(TXTPERBOXIMEI, value);
    }

    /**
     * Gets the attribute value for txtImeiSerial, using the alias name txtImeiSerial.
     * @return the value of txtImeiSerial
     */
    public String gettxtImeiSerial() {
        return (String) getAttributeInternal(TXTIMEISERIAL);
    }

    /**
     * Sets <code>value</code> as the attribute value for txtImeiSerial.
     * @param value value to set the txtImeiSerial
     */
    public void settxtImeiSerial(String value) {
        setAttributeInternal(TXTIMEISERIAL, value);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getInSpbox() {
        return (RowIterator) getAttributeInternal(INSPBOX);
    }

    /**
     * @return the associated entity oracle.jbo.server.EntityImpl.
     */
    public EntityImpl getInItems() {
        return (EntityImpl) getAttributeInternal(INITEMS);
    }

    /**
     * Sets <code>value</code> as the associated entity oracle.jbo.server.EntityImpl.
     */
    public void setInItems(EntityImpl value) {
        setAttributeInternal(INITEMS, value);
    }


    /**
     * @param packingseq key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Integer packingseq) {
        return new Key(new Object[] { packingseq });
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        setERPSolPKColumnName("Packingseq");
        setERPSolPKSeqName("IN_SET_PACKING_SEQ");
        setLocationid(ERPSolGlobClassModel.doGetUserLocationCode());
//        setStoreid(ERPSolGlobClassModel.doGetUserStoreCode());
//        System.out.println(attributeList.getAttribute("PDate"));
        super.create(attributeList);
    }

    /**
     * Add entity remove logic in this method.
     */
    public void remove() {
        super.remove();
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        System.out.println("in set pack insert main");
        if (operation==DML_INSERT) {
            System.out.println("in set pack insert");
            String pkValue=" packing_id('"+ERPSolGlobClassModel.doGetUserCompanyCode()+"','"+ERPSolGlobClassModel.doGetUserLocationCode()+"',TO_DATE('"+getPdate()+"','YYYY-MM-DD'))";
            String result= ERPSolGlobClassModel.doGetERPSolPrimaryKeyValueModel(getDBTransaction(), pkValue, "dual", null, null);
            populateAttributeAsChanged(PCKID, result);
        }   
        super.doDML(operation, e);
    }
    public void doSetErpSolStartEndDate(String pDate) {
        try {
        Calendar calendar = Calendar.getInstance();
        java.util.Date UtilDate = new SimpleDateFormat("yyyy-MM-dd").parse(pDate);
        calendar.setTime(UtilDate);
        String smonth="";
        String emonth="";
        String eday  ="";
        String eyear="";
        String syear="";
        java.util.Date WtyStart;
        java.util.Date  WtyEnd;
        Integer day=calendar.get(Calendar.DAY_OF_MONTH);
        
        if (day<11) {
           calendar.add(Calendar.MONTH, 1);
        }
        else {
           calendar.add(Calendar.MONTH, 2);
        }
        //       calendar.add(Calendar.MONTH, 1);
        syear=""+calendar.get(Calendar.YEAR);
        
        smonth=""+ (calendar.get(Calendar.MONTH)+1);
        WtyStart=new SimpleDateFormat("yyyy-MM-dd").parse(syear+"-"+smonth+"-01");
        calendar.add(Calendar.MONTH, 11);
        eyear=""+(calendar.get(Calendar.YEAR));
        eday=""+calendar.getActualMaximum(Calendar.DAY_OF_MONTH);
        
        emonth=""+(calendar.get(Calendar.MONTH)+1);
        
        WtyEnd=new SimpleDateFormat("yyyy-MM-dd").parse(eyear+"-"+emonth+"-"+eday);
        
        
        
        java.sql.Date sqlStartDate = new java.sql.Date(WtyStart.getTime());
        java.sql.Date sqlEndate = new java.sql.Date(WtyEnd.getTime());
        
        Date jboStartDate = new oracle.jbo.domain.Date(sqlStartDate);
        Date jboEndDate = new oracle.jbo.domain.Date(sqlEndate);
        
        System.out.println(jboStartDate);
        System.out.println(jboEndDate);
        setPurchdate(jboStartDate);
        setExpdate(jboEndDate);
        }
        catch (Exception exc){
            exc.printStackTrace();
        }
    }
}

