package erpsolwcp.erpsolwcpmodel.erpsolwcpeo;

import erpsolglob.erpsolglobmodel.erpsolglobclasses.ERPSolGlobalsEntityImpl;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.domain.Date;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu May 26 13:35:52 PKT 2022
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class InWarrantyBoxLinesImpl extends ERPSolGlobalsEntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        BoxLinesseq,
        Boxheaderseq,
        CreatedDate,
        CreatedBy,
        ModifiedBy,
        ModifiedDate,
        ImeiNo,
        InWarrantyBoxHeader;
        static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int BOXLINESSEQ = AttributesEnum.BoxLinesseq.index();
    public static final int BOXHEADERSEQ = AttributesEnum.Boxheaderseq.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int MODIFIEDBY = AttributesEnum.ModifiedBy.index();
    public static final int MODIFIEDDATE = AttributesEnum.ModifiedDate.index();
    public static final int IMEINO = AttributesEnum.ImeiNo.index();
    public static final int INWARRANTYBOXHEADER = AttributesEnum.InWarrantyBoxHeader.index();

    /**
     * This is the default constructor (do not remove).
     */
    public InWarrantyBoxLinesImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("erpsolwcp.erpsolwcpmodel.erpsolwcpeo.InWarrantyBoxLines");
    }


    /**
     * Gets the attribute value for BoxLinesseq, using the alias name BoxLinesseq.
     * @return the value of BoxLinesseq
     */
    public Integer getBoxLinesseq() {
        return (Integer) getAttributeInternal(BOXLINESSEQ);
    }

    /**
     * Sets <code>value</code> as the attribute value for BoxLinesseq.
     * @param value value to set the BoxLinesseq
     */
    public void setBoxLinesseq(Integer value) {
        setAttributeInternal(BOXLINESSEQ, value);
    }

    /**
     * Gets the attribute value for Boxheaderseq, using the alias name Boxheaderseq.
     * @return the value of Boxheaderseq
     */
    public Integer getBoxheaderseq() {
        return (Integer) getAttributeInternal(BOXHEADERSEQ);
    }

    /**
     * Sets <code>value</code> as the attribute value for Boxheaderseq.
     * @param value value to set the Boxheaderseq
     */
    public void setBoxheaderseq(Integer value) {
        setAttributeInternal(BOXHEADERSEQ, value);
    }


    /**
     * Gets the attribute value for CreatedDate, using the alias name CreatedDate.
     * @return the value of CreatedDate
     */
    public Date getCreatedDate() {
        return (Date) getAttributeInternal(CREATEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedDate.
     * @param value value to set the CreatedDate
     */
    public void setCreatedDate(Date value) {
        setAttributeInternal(CREATEDDATE, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the value of CreatedBy
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for ModifiedBy, using the alias name ModifiedBy.
     * @return the value of ModifiedBy
     */
    public String getModifiedBy() {
        return (String) getAttributeInternal(MODIFIEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for ModifiedBy.
     * @param value value to set the ModifiedBy
     */
    public void setModifiedBy(String value) {
        setAttributeInternal(MODIFIEDBY, value);
    }

    /**
     * Gets the attribute value for ModifiedDate, using the alias name ModifiedDate.
     * @return the value of ModifiedDate
     */
    public Date getModifiedDate() {
        return (Date) getAttributeInternal(MODIFIEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ModifiedDate.
     * @param value value to set the ModifiedDate
     */
    public void setModifiedDate(Date value) {
        setAttributeInternal(MODIFIEDDATE, value);
    }

    /**
     * Gets the attribute value for ImeiNo, using the alias name ImeiNo.
     * @return the value of ImeiNo
     */
    public Long getImeiNo() {
        return (Long) getAttributeInternal(IMEINO);
    }

    /**
     * Sets <code>value</code> as the attribute value for ImeiNo.
     * @param value value to set the ImeiNo
     */
    public void setImeiNo(Long value) {
        setAttributeInternal(IMEINO, value);
    }

    /**
     * @return the associated entity InWarrantyBoxHeaderImpl.
     */
    public InWarrantyBoxHeaderImpl getInWarrantyBoxHeader() {
        return (InWarrantyBoxHeaderImpl) getAttributeInternal(INWARRANTYBOXHEADER);
    }

    /**
     * Sets <code>value</code> as the associated entity InWarrantyBoxHeaderImpl.
     */
    public void setInWarrantyBoxHeader(InWarrantyBoxHeaderImpl value) {
        setAttributeInternal(INWARRANTYBOXHEADER, value);
    }


    /**
     * @param boxLinesseq key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Integer boxLinesseq) {
        return new Key(new Object[] { boxLinesseq });
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        setERPSolPKColumnName("BoxLinesseq");
        setERPSolPKSeqName("IN_WARRANTY_BOX_LINES_SEQ");          
        super.create(attributeList);
    }

    /**
     * Add entity remove logic in this method.
     */
    public void remove() {
        super.remove();
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        super.doDML(operation, e);
    }
}

