package erpsolwcp.erpsolwcpmodel.erpsolwcpqvo;

import oracle.jbo.Row;
import oracle.jbo.ViewObject;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Nov 30 11:16:10 PKT 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class VWScanImeiBoxQVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        Pk,
        Imei,
        BoxNo;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int PK = AttributesEnum.Pk.index();
    public static final int IMEI = AttributesEnum.Imei.index();
    public static final int BOXNO = AttributesEnum.BoxNo.index();

    /**
     * This is the default constructor (do not remove).
     */
    public VWScanImeiBoxQVORowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute Pk.
     * @return the Pk
     */
    public Integer getPk() {
        return (Integer) getAttributeInternal(PK);
    }

    /**
     * Gets the attribute value for the calculated attribute Imei.
     * @return the Imei
     */
    public String getImei() {
        return (String) getAttributeInternal(IMEI);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Imei.
     * @param value value to set the  Imei
     */
    public void setImei(String value) {
        System.out.println(value);
//        setAttributeInternal(IMEI, value);
         
        ViewObject ERPSolvo=getDBTransaction().getRootApplicationModule().findViewObject("InSpdetlDetCRUD");
        Row ERPsolrow=ERPSolvo.createRow();
        ERPsolrow.setAttribute("ImeiNo", value);
        ERPSolvo.insertRow(ERPsolrow);

//        ERPSolvo.setCurrentRow(ERPsolrow);
        
//        ERPSolvo.executeQuery();
        
//        setAttributeInternal(BOXNO, value);
           
    }

    /**
     * Gets the attribute value for the calculated attribute BoxNo.
     * @return the BoxNo
     */
    public String getBoxNo() {
        return (String) getAttributeInternal(BOXNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute BoxNo.
     * @param value value to set the  BoxNo
     */
    public void setBoxNo(String value) {
        /*
        if (value==null) {
            return;
       }*/
        System.out.println("hello");
        value=value.toUpperCase();
        System.out.println("hello-2");
        ViewObject ERPSolvo=getDBTransaction().getRootApplicationModule().findViewObject("InSpboxDetCRUD");
        Row ERPsolrow=ERPSolvo.createRow();
        ERPsolrow.setAttribute("Boxno", value);
        ERPSolvo.insertRow(ERPsolrow);
        ERPSolvo.setCurrentRow(ERPsolrow);
//        ERPSolvo.executeQuery();
//        setAttributeInternal(BOXNO, value);
    }
}

