package erpsolwcp.erpsolwcpmodel.erpsolwcpvo.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Dec 28 23:58:44 PKT 2021
// ---------------------------------------------------------------------
public interface InSetPackingRepackView extends ViewObject {
    void doSuperviseWarrantyCard();
}

