package erpsolwcp.erpsolwcpmodel.erpsolwcpvo.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Dec 02 07:38:12 PKT 2021
// ---------------------------------------------------------------------
public interface InSetPackingView extends ViewObject {
    void doSuperviseWarrantyCard();
}

