package erpsolwcp.erpsolwcpmodel.erpsolwcpvo.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu May 26 15:41:16 PKT 2022
// ---------------------------------------------------------------------
public interface InWarrantyBoxHeaderView extends ViewObject {
    void doSuperviseWarrantyBox();

    void doERPCopyRow();
}

